
#key: u - up, d - down, l - left, r - right, / - diagonal up right, \\ - diagonal down right, . - dot, b - begin (pen down), e - end (pen up), s - stop.
#characters are typically 2 units tall and unit wide. (except for 'm' and 'w')

class Characters:
    def __init__(self):
        self.char_dict = {
            #example: for 'a' the instructions are: begin, up, up, right, down, left, end, right, begin, down, end, stop
            'a': 'buurdlerbdes',
            'b': 'buureldb/eldb\\les',
            'c': 'ub\\elub/es',
            'd': 'buu\\edlb/es',
            'e': 'brelburelbures',
            'f': 'burelbures',
            'g': 'b/eldbuures',
            'h': 'burelbuerbddes',
            'i': 'buues',
            'j': 'ub\\uules',
            'k': 'bu\\eulb/eldbues',
            'l': 'brelbuues',
            'm': 'buu\\deub/dders',
            'n': 'buu\\deubues',
            'o': 'buurddles',
            'p': 'buu\\les',
            'q': 'buurdelb\\uedbles',
            'r': 'buurdl\\es',
            's': 'ub/edbledb/es',
            't': 'uubredlb/edlb\\es',
            'u': 'buueddbruues',
            'v': 'ub\\eulbuerbddes',
            'w': 'uubd\\uueddb/ues',
            'x': 'uubd\\elb/ues',
            'y': 'uubdruedldb/es',
            'z': 'uub\\l\\es',
            '0': 'buurddl/elb/es',
            '1': 'rbuueldb/es',
            '2': 'uubrdldres',
            '3': 'brulerbules',
            '4': 'ub/dlerbdes',
            '5': 'brelub\\eulbures',
            '6': 'buuedb\\les',
            '7': 'ub/ledbdes',
            '8': 'burelburddles',
            '9': 'uburdlerbdes',
            '.': 'b.es',
            ',': 'b/es',
            ':': 'b.eub.es',
            ';': 'b/elub.es',
            '!': 'b.eubues',
            '?': 'b.eubules',
            '(': 'bu/eddlbres',
            ')': 'uub\\dles',
            '"': 'ubuerbdes',
            "'": 'ubues',
            '<': 'b/edlbres',
            '>': 'ub\\elbres',
            '-': 'ubres',
            '_': 'bres',
            '=': 'brelubres',
            '+': 'uub\\ledb/el',
            '@': 'burd.leub/des',
            '%': 'b/edb.elub.es',
            '^': 'ub/des',
            '&': 'b/uldrelbdeub\\es',
            "*": 'ub/elb\\es',
            '`': 'ub\\ues',
            '~': 'ubu\\ues',
            '/': 'b/elb/es',
            '\\': 'uub\\elb\\es',
            '|': 'uurbddes',
            '♥': 'uub\\/uldeubldes',
            '😀': 'uub.errb.edllb\\/es'
        }